# Generated by Django 2.2.5 on 2020-11-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(default='', max_length=20)),
                ('lname', models.CharField(default='', max_length=20)),
                ('category', models.CharField(default='Student', max_length=10)),
                ('gender', models.CharField(default='', max_length=15)),
                ('department', models.CharField(default='', max_length=30)),
                ('Class', models.CharField(default='', max_length=15)),
                ('email', models.EmailField(default='', max_length=30)),
                ('password', models.CharField(default='', max_length=30)),
                ('re_password', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
