# Generated by Django 2.2.5 on 2020-11-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('lname', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('category', models.CharField(blank=True, default='Student', max_length=10, null=True)),
                ('gender', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('department', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('Class', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=30, null=True)),
                ('password', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('re_password', models.CharField(blank=True, default='', max_length=30, null=True)),
            ],
        ),
    ]
